<?php


    namespace MultilangAny\Connectors;

    use MultilangAny\AbstractConnector;

    /**
     * Class ExampleCodeignitorV3
     *
     * @package MultilangAny\Connectors
     * @author Fabian Hesse <pleinx0@gmail.com>
     * Visit me on : https://github.com/pleinx
     */
    class ExampleCodeignitorV3 extends AbstractConnector {

        // In Progress...

        /**
         * @return string
         */
        function getLanguage () {
            return parent::getLanguage(); // TODO: Change the autogenerated stub
        }
    }