<?php

    namespace TranslatorAPI\Connectors;

    use TranslatorAPI\AbstractConnector;

    /**
     * Class ExampleSlimFrameworkV3
     *
     * @package TranslatorAPI\Connectors
     * @author Fabian Hesse <pleinx0@gmail.com>
     * Visit me on : https://github.com/pleinx
     */
    class ExampleSlimFrameworkV3 extends AbstractConnector {

        // In Progress...

        /**
         * @return string
         */
        function getLanguage () {
            return parent::getLanguage(); // TODO: Change the autogenerated stub
        }
    }